/*
 * SPDX-License-Identifier: GPL-3.0-or-later
 * SPDX-FileCopyrightText: 2016 Juan Pablo Lozano <libredeb@gmail.com>
 */
namespace Vinyl.Utils {
    public enum Screen {
        MAIN,
        LIBRARY_MENU,
        LIBRARY,
        NOW_PLAYING,
        RADIO,
        TRANSITION_TO_LIBRARY_MENU,
        TRANSITION_FROM_LIBRARY_MENU_TO_MAIN,
        CATEGORY_LIST,
        TRANSITION_TO_CATEGORY_LIST,
        TRANSITION_FROM_CATEGORY_LIST_TO_LIBRARY_MENU,
        TRANSITION_TO_LIBRARY,
        TRANSITION_FROM_LIBRARY_TO_LIBRARY_MENU,
        TRANSITION_TO_MAIN,
        TRANSITION_TO_NOW_PLAYING,
        TRANSITION_FROM_NOW_PLAYING_TO_LIBRARY,
        TRANSITION_FROM_NOW_PLAYING_TO_MAIN,
        TRANSITION_TO_RADIO,
        TRANSITION_FROM_RADIO_TO_MAIN,
        RADIO_NOW_PLAYING,
        TRANSITION_TO_RADIO_NOW_PLAYING,
        TRANSITION_FROM_RADIO_NOW_PLAYING_TO_RADIO,
        TRANSITION_FROM_RADIO_NOW_PLAYING_TO_MAIN,
        SEARCH,
        TRANSITION_TO_SEARCH,
        TRANSITION_FROM_SEARCH_TO_MAIN,
        TRANSITION_FROM_NOW_PLAYING_TO_SEARCH
    }

    public enum InputAction {
        UP,
        DOWN,
        LEFT,
        RIGHT,
        CONFIRM,
        BACK
    }
}
